### ISSUE TITLE
How to infer from multiple images and how to train

### ISSUE THREAD

**Issue by take0212** [Alvin0629/TransFlow#1]
Thank you for publishing the code.

Question 1.
Is it possible to infer from multiple images?
I believe the advantage of TransFlow is that it can be associated for a long time in the time direction.
On the other hand, only two images are inputed in line 85 of infer.py.

Question 2.
Will the training script be also published?

Thank you in advance for your answer.

**Comment by Alvin0629** [comment]
Thanks for the questions. Currently it only supports inference from two inputs in a batch, and the temporal constraints only apply to training. But I have the plan to add multi-frame inference as well, it could be updated along with training later with journal paper acceptance.

**Comment by take0212** [comment]
Thanks for your reply.

I look forward to be added multi-frame inference.
I also look forward to be added learning.

Thank you for sharing the model files as well.

I look forward to your update announcements.

**Comment by take0212** [comment]
I have one more request.

Could you please specify the license?
I would like a license that allows commercial use.

Thank you very much.

**Comment by Alvin0629** [comment]
> I have one more request.
> 
> Could you please specify the license? I would like a license that allows commercial use.
> 
> Thank you very much.

It applys Apache License Version 2.0, thank you.

**Comment by take0212** [comment]
Thank you for defining the license.
It is Apache License Version 2.0, so we can use it for commercial purposes.
I appreciated you.

You can also add the license file.
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

Thank you very much.

**Comment by Alvin0629** [comment]
> Thank you for defining the license. It is Apache License Version 2.0, so we can use it for commercial purposes. I appreciated you.
> 
> You can also add the license file. https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository
> 
> Thank you very much.

updated, thanks
