### ISSUE TITLE
无法访问GoogleDrive链接

### ISSUE THREAD

**Issue by Wenlve-Zhou** [Alvin0629/TransFlow#2]
您好！十分感谢您出色的工作！您提供的GoogleDrive链接无法访问，能否麻烦您提供百度云盘的链接，十分感谢！

**Comment by Alvin0629** [comment]
> 您好！十分感谢您出色的工作！您提供的GoogleDrive链接无法访问，能否麻烦您提供百度云盘的链接，十分感谢！

Link has been reshared, pls have a look

**Comment by Wenlve-Zhou** [comment]
Thank you so much!

**Comment by Wenlve-Zhou** [comment]
抱歉，想打扰一下。在train_flow.py文件中，from configs.things import get_cfg报错了。似乎configs.things没有上传，请问这是什么问题呢？是这部分代码不公开吗？

**Comment by Alvin0629** [comment]
> 抱歉，想打扰一下。在train_flow.py文件中，from configs.things import get_cfg报错了。似乎configs.things没有上传，请问这是什么问题呢？是这部分代码不公开吗？

Thanks for finding this! Seems it got lost during upload. Just found it and re-uploaded.
